theme: jekyll-theme-minimal
title: Chemische clusters en veiligheid - Een clusterspecifieke rangschikking van veiligheidsparameters
description: Aan de slag!
[Klik hier om het volledige onderzoeksrapport te lezen](https://github.com/Clustersafety/Rangschikking_veiligheidsparameters/blob/main/Onderzoeksrapport%20-%20Een%20clusterspecifieke%20rangschikking%20van%20veiligheidsparameters%20-%20Augustus%202022.pdf)
[Klik hier om naar de Excel tool te gaan](https://github.com/Clustersafety/Rangschikking_veiligheidsparameters/blob/bff3050e2d703298a8edfbc41445b0a195d92de8/TEST.xlsx)
